<?php

namespace frontend\models\work\general;

use common\helpers\DateFormatter;
use common\models\scaffold\People;
use InvalidArgumentException;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use function common\models\work\general\mb_substr;

class PeopleWork extends People
{
    const FIO_FULL = 1;
    const FIO_SURNAME_INITIALS = 2;
    const FIO_WITH_POSITION = 3;

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => function() {
                    return date('Y-m-d H:i:s');
                },
            ],
        ];
    }

    public static function getFioTypes()
    {
        return [
            self::FIO_FULL => 'ФИО полностью',
            self::FIO_SURNAME_INITIALS => 'Фамилия и инициалы',
            self::FIO_WITH_POSITION => 'ФИО полностью и должность с местом работы в скобках',
        ];
    }

    public function getFIO($type)
    {
        switch ($type) {
            case self::FIO_FULL:
                return $this->getFullFio();
            case self::FIO_SURNAME_INITIALS:
                return $this->getSurnameInitials();
            case self::FIO_WITH_POSITION:
                return $this->getFioPosition();
            default:
                throw new InvalidArgumentException('Неизвестный тип вывода ФИО');
        }
    }

    public function getFullFio()
    {
        return "$this->surname $this->firstname $this->patronymic";
    }

    public function getSurnameInitials()
    {
        return $this->surname
            . ' ' . mb_substr($this->firstname, 0, 1)
            . '. ' . ($this->patronymic ? mb_substr($this->patronymic, 0, 1) . '.' : '');
    }

    public function getFioPosition()
    {
        return 'stub';
    }

    public function getSexString()
    {
        switch ($this->sex) {
            case 0:
                return 'Мужской';
            case 1:
                return 'Женский';
            default:
                return 'Другое';
        }
    }

    public function beforeValidate()
    {
        $this->firstname = str_replace(' ', '', $this->firstname);
        $this->surname = str_replace(' ', '', $this->surname);
        $this->patronymic = str_replace(' ', '', $this->patronymic);

        if ($this->birthdate !== '') {
            $this->birthdate = DateFormatter::format($this->birthdate, DateFormatter::dmY_dot, DateFormatter::Ymd_dash);
        }

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function inMainCompany()
    {
        return $this->company_id == Yii::$app->params["mainCompanyId"];
    }
}
