<?php

namespace frontend\forms\journal;

use common\Model;
use common\repositories\educational\GroupProjectThemesRepository;
use common\repositories\educational\TrainingGroupLessonRepository;
use common\repositories\educational\TrainingGroupRepository;
use common\repositories\educational\VisitRepository;
use DomainException;
use frontend\models\work\educational\journal\ParticipantLessons;
use frontend\models\work\educational\journal\VisitLesson;
use frontend\models\work\educational\journal\VisitWork;
use frontend\models\work\educational\training_group\GroupProjectThemesWork;
use frontend\models\work\educational\training_group\TrainingGroupWork;
use Yii;
use yii\log\LogRuntimeException;

/**
 * @property TrainingGroupWork $trainingGroupWork
 */

class JournalForm extends Model
{
    /** @var VisitWork[] $visits */
    public array $visits;
    public $groupId;
    public $trainingGroup;

    /** @var ParticipantLessons[] $participantLessons */
    public array $participantLessons = [];

    /** @var GroupProjectThemesWork[] $availableThemes */
    public array $availableThemes;

    public function rules()
    {
        return [
            ['participantLessons', 'safe']
        ];
    }

    public function __construct(
        int $groupId = null,
        $config = []
    )
    {
        parent::__construct($config);
        if (!is_null($groupId)) {
            $this->groupId = $groupId;
            $this->trainingGroup = (Yii::createObject(TrainingGroupRepository::class))->get($this->groupId);
            $this->visits = (Yii::createObject(VisitRepository::class))->getByTrainingGroup($this->groupId);
            $this->availableThemes = (Yii::createObject(GroupProjectThemesRepository::class))->getProjectThemesFromGroup($this->groupId);

            foreach ($this->visits as $visit) {
                /** @var VisitWork $visit */
                $lessons = VisitLesson::fromString($visit->lessons, Yii::createObject(TrainingGroupLessonRepository::class));
                $this->participantLessons[] = new ParticipantLessons(
                    $visit->training_group_participant_id,
                    $lessons,
                    $visit->trainingGroupParticipantWork->group_project_themes_id,
                    $visit->trainingGroupParticipantWork->points,
                    $visit->trainingGroupParticipantWork->success
                );
            }
        }

        foreach ($this->participantLessons as $participantLesson) {
            $participantLesson->sortLessons();
        }
    }

    public function load($data, $formName = null)
    {
        // Дозагружаем VisitLesson и доп данные для ParticipantLessons вручную, ActiveRecord не справляется сам
        $newParticipantLessons = [];
        $visitLessons = $data["VisitLesson"];
        $participantData = $data["ParticipantLessons"];

        if (is_array($visitLessons) && is_array($participantData)) {
            if (count($visitLessons) !== count($participantData)) {
                throw new DomainException('Техническая ошибка сервера. Закройте страницу и попробуйте еще раз');
            }

            foreach ($visitLessons as $index => $visitLesson) {
                $lessonArray = [];
                foreach ($visitLesson as $lesson) {
                    $lessonArray[] = new VisitLesson(
                        $lesson["lessonId"],
                        $lesson["status"],
                        (Yii::createObject(TrainingGroupLessonRepository::class))->get($lesson["lessonId"])
                    );
                }

                $groupProjectThemeId = !empty($participantData[$index]['groupProjectThemeId']) ?
                    (int)$participantData[$index]['groupProjectThemeId'] :
                    null;
                $newParticipantLessons[] = new ParticipantLessons(
                    $index,
                    $lessonArray,
                    $groupProjectThemeId,
                    (int)$participantData[$index]['points'],
                    (int)$participantData[$index]['successFinishing']
                );
            }
            $this->participantLessons = $newParticipantLessons;
        }
        return parent::load($data, $formName); // TODO: Change the autogenerated stub
    }

    /**
     * Возвращает номер учебной группы
     * @return mixed|string|null
     */
    public function getTrainingGroupNumber()
    {
        return $this->trainingGroup ? $this->trainingGroup->number : '';
    }

    /**
     * Иконка архивного статуса
     * @return string
     */
    public function getRawArchiveGroup()
    {
        return $this->trainingGroup ? $this->trainingGroup->getRawArchive() : '';
    }


}