<?php

namespace frontend\models\work\regulation;

use common\events\EventTrait;
use common\helpers\DateFormatter;
use common\helpers\files\FilesHelper;
use common\helpers\StringFormatter;
use common\models\scaffold\Regulation;
use common\repositories\general\FilesRepository;
use frontend\models\work\general\FilesWork;
use InvalidArgumentException;
use Yii;
use yii\helpers\Url;

class RegulationWork extends Regulation
{
    use EventTrait;
    const STATE_ACTIVE = 1;
    const STATE_EXPIRE = 2;

    public $expires; //документ, отменяющий текущее положение

    /**
     * Переменные для input-file в форме
     */
    public $scanFile;

    public function __construct($config = [])
    {
        parent::__construct($config);
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            [['scanFile'], 'file', 'skipOnEmpty' => true,
                'extensions' => 'png, jpg, pdf, zip, rar, 7z, tag, txt'],
        ]);
    }

    public static function states()
    {
        return [
            self::STATE_ACTIVE => 'Актуально',
            self::STATE_EXPIRE => 'Утратило силу',
        ];
    }

    public function getStates()
    {
        $statuses = self::states();
        if (!array_key_exists($this->state, $statuses)) {
            throw new InvalidArgumentException('Неизвестный статус положения');
        }

        return $statuses[$this->state];
    }

    /**
     * Возвращает массив
     * link => форматированная ссылка на документ
     * id => ID записи в таблице files
     * @param $filetype
     * @return array
     * @throws \yii\base\InvalidConfigException
     */
    public function getFileLinks($filetype)
    {
        if (!array_key_exists($filetype, FilesHelper::getFileTypes())) {
            throw new InvalidArgumentException('Неизвестный тип файла');
        }

        $addPath = '';
        switch ($filetype) {
            case FilesHelper::TYPE_SCAN:
                $addPath = FilesHelper::createAdditionalPath(RegulationWork::tableName(), FilesHelper::TYPE_SCAN);
                break;
        }

        $files = (Yii::createObject(FilesRepository::class))->get(self::tableName(), $this->id, $filetype);
        $links = [];
        if (count($files) > 0) {
            foreach ($files as $file) {
                /** @var FilesWork $file */
                $links[] = [
                    'link' => StringFormatter::stringAsLink(
                        FilesHelper::getFilenameFromPath($file->filepath),
                        Url::to(['get-file', 'filepath' => $addPath . $file->filepath])
                    ),
                    'id' => $file->id
                ];
            }
        }

        return $links;
    }

    // ТОЛЬКО для предварительной обработки полей. Остальные действия - через Event
    public function beforeValidate()
    {
        $this->creator_id = 1/*Yii::$app->user->identity->getId()*/;
        $this->state = RegulationWork::STATE_ACTIVE;
        $this->date = DateFormatter::format($this->date, DateFormatter::dmY_dot, DateFormatter::Ymd_dash);
        $this->ped_council_date = DateFormatter::format($this->ped_council_date, DateFormatter::dmY_dot, DateFormatter::Ymd_dash);
        $this->par_council_date = DateFormatter::format($this->par_council_date, DateFormatter::dmY_dot, DateFormatter::Ymd_dash);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}
