<?php

namespace common\models\work\regulation;

use common\helpers\DateFormatter;
use common\models\scaffold\Regulation;

class RegulationWork extends Regulation
{
    // ТОЛЬКО для предварительной обработки полей. Остальные действия - через Event
    public function beforeValidate()
    {
        var_dump('boobs');
        $this->creator_id = 1/*Yii::$app->user->identity->getId()*/;
        $this->date = DateFormatter::format($this->date, DateFormatter::dmY_dot, DateFormatter::Ymd_dash);
        $this->ped_council_date = DateFormatter::format($this->ped_council_date, DateFormatter::dmY_dot, DateFormatter::Ymd_dash);
        $this->par_council_date = DateFormatter::format($this->par_council_date, DateFormatter::dmY_dot, DateFormatter::Ymd_dash);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}
