<?php

namespace frontend\models\work\educational;

use common\events\EventTrait;
use common\helpers\DateFormatter;
use common\helpers\files\FilesHelper;
use common\helpers\StringFormatter;
use common\models\scaffold\TrainingProgram;
use common\repositories\general\FilesRepository;
use frontend\models\work\general\FilesWork;
use InvalidArgumentException;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\helpers\Url;

class TrainingProgramWork extends TrainingProgram
{
    use EventTrait;

    public $mainFile;
    public $docFiles;
    public $contractFile;
    public $fileUtp;

    public $branches;

    public function rules()
    {
        return array_merge(parent::rules(), [
                [['branches'], 'safe'],
                [['mainFile'], 'file', 'skipOnEmpty' => true,
                    'extensions' => 'jpg, png, pdf, doc, docx, zip, rar, 7z, tag'],
                [['docFiles'], 'file', 'skipOnEmpty' => true, 'maxFiles' => 10,
                    'extensions' => 'jpg, png, pdf, doc, docx, zip, rar, 7z, tag'],
                [['contractFile'], 'file', 'skipOnEmpty' => true,
                    'extensions' => 'ppt, pptx, xls, xlsx, pdf, png, jpg, doc, docx, zip, rar, 7z, tag, txt'],
                [['fileUtp'], 'file', 'extensions' => 'xls, xlsx', 'skipOnEmpty' => true],
            ]
        );
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => function() {
                    return date('Y-m-d H:i:s');
                },
            ],
        ];
    }

    public function beforeValidate()
    {
        $this->ped_council_date = DateFormatter::format($this->ped_council_date, DateFormatter::dmY_dot, DateFormatter::Ymd_dash);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function getFullDirectionName()
    {
        return Yii::$app->thematicDirection->getFullnameList()[$this->thematic_direction];
    }

    /**
     * Возвращает массив
     * link => форматированная ссылка на документ
     * id => ID записи в таблице files
     * @param $filetype
     * @return array
     * @throws \yii\base\InvalidConfigException
     */
    public function getFileLinks($filetype)
    {
        if (!array_key_exists($filetype, FilesHelper::getFileTypes())) {
            throw new InvalidArgumentException('Неизвестный тип файла');
        }

        $addPath = '';
        switch ($filetype) {
            case FilesHelper::TYPE_MAIN:
                $addPath = FilesHelper::createAdditionalPath(TrainingProgramWork::tableName(), FilesHelper::TYPE_MAIN);
                break;
            case FilesHelper::TYPE_DOC:
                $addPath = FilesHelper::createAdditionalPath(TrainingProgramWork::tableName(), FilesHelper::TYPE_DOC);
                break;
        }

        return FilesHelper::createFileLinks($this, $filetype, $addPath);
    }
}