<?php

namespace backend\forms;

use common\Model;
use common\repositories\general\UserRepository;
use common\repositories\rubac\PermissionFunctionRepository;
use frontend\models\work\rubac\PermissionFunctionWork;
use Yii;

class TokensForm extends Model
{
    public array $users;
    public array $permissions;

    public $userId;
    public $permissionId;
    public $branch;
    public $duration;

    public function __construct($config = [])
    {
        parent::__construct($config);
        $this->users = (Yii::createObject(UserRepository::class))->getAll();
        $this->permissions = (Yii::createObject(PermissionFunctionRepository::class))->getAllPermissions();
    }

    public function rules()
    {
        return [
            [['userId', 'permissionId', 'duration'], 'integer'],
            [['branch'], 'safe']
        ];
    }

    public function beforeValidate()
    {
        if ($this->branch == '') {
            $this->branch = null;
        }

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}